version: '3'

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPaSSword
      POSTGRES_DB: cdb-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: Backend
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cdb-dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresPaSSword

volumes:
  postgres-data:

